In [3]:
from baselines.ddpg.memory import Memory, array_min2d, RingBuffer
import numpy as np
import sys

In [4]:
sys.path

['',
 '/home/daniel/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/devel/lib/python2.7/dist-packages',
 '/opt/ros/kinetic/lib/python2.7/dist-packages',
 '/home/daniel/anaconda3/envs/NIPS2017/lib/python36.zip',
 '/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6',
 '/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6/lib-dynload',
 '/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6/site-packages',
 '/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg',
 '/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6/site-packages/IPython/extensions',
 '/home/daniel/.ipython']

In [3]:
memory = Memory(10,(1,3),(1,3))

In [38]:
hehe = np.random.random_integers(1, 4)

/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  if __name__ == '__main__':


In [29]:
hehe

4

In [9]:
memory.nb_entries

2

In [10]:
memory.append([1,2,3],[4,5,6],4,[2,3,4],0)

In [11]:
memory.sample(1)

{'actions': array([[[ 4.,  5.,  6.]]], dtype=float32),
 'obs0': array([[[ 1.,  2.,  3.]]], dtype=float32),
 'obs1': array([[[ 2.,  3.,  4.]]], dtype=float32),
 'rewards': array([[ 4.]], dtype=float32),
 'terminals1': array([[ 0.]], dtype=float32)}

In [13]:
array_min2d([2,4])

array([[2],
       [4]])

In [14]:
lotr = RingBuffer(10,(2,1))

In [18]:
lotr.length

0

In [44]:
samp = np.array([[2, 1]])
lul = np.array([[2],[1]])

In [42]:
samp.shape

(1, 2)

In [46]:
lul.shape


(2, 1)

In [52]:
kek = lul.T
kek

array([[2, 1]])

In [17]:
lista = np.array([[1],[2]])

In [11]:
lista_array = array_min2d(lista)
lista_array

array([[1],
       [2],
       [3]])

In [12]:
np.savetxt('test.txt', lista_array)

In [13]:
lista_open= np.loadtxt('test.txt')
lista_open

array([ 1.,  2.,  3.])

In [30]:
np.zeros((3,)+(2,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [31]:
(3,)+(2,3)

(3, 2, 3)

In [34]:
(0)%10

1

In [86]:
hello = np.random.random_integers(5, size=2)
hello

/home/daniel/anaconda3/envs/NIPS2017/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  if __name__ == '__main__':


array([4, 1])

In [23]:
lotr[0]

array([[ 1.],
       [ 2.]], dtype=float32)

In [28]:
lotr.data

array([[[ 1.],
        [ 2.]],

       [[ 1.],
        [ 2.]],

       [[ 1.],
        [ 2.]],

       [[ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.]]], dtype=float32)

In [87]:
lotr.get_batch(hello)

array([[[ 0.],
        [ 0.]],

       [[ 1.],
        [ 2.]]], dtype=float32)