In [1]:
import numpy as np

In [2]:
A = np.mat("3 1; 1 0")
print("A : \n", A)

A : 
 [[3 1]
 [1 0]]


In [3]:
print("Eigenvalues: ", np.linalg.eigvals(A))

Eigenvalues:  [ 3.30277564 -0.30277564]


In [52]:
eigenvalue,eigenvector= np.linalg.eig(A)

In [53]:
print("Eigenvalues: {} \n Eigenvectors: {}".format(eigenvalue,eigenvector))

Eigenvalues: [ 3.30277564 -0.30277564] 
 Eigenvectors: [[ 0.95709203 -0.28978415]
 [ 0.28978415  0.95709203]]


In [12]:
np.dot(A,eigenvector(1,:))

SyntaxError: invalid syntax (<ipython-input-12-010cd9e9e4ca>, line 1)

In [54]:
eigenvector[0,:]

matrix([[ 0.95709203, -0.28978415]])

In [55]:
eigenvalue[0]

3.3027756377319943

In [19]:
A.__call__=2

In [58]:
np.matmul(A,eigenvector[:,0])

matrix([[ 3.16106023],
        [ 0.95709203]])

In [63]:
eigenvalue[0]*eigenvector[:,0]

matrix([[ 3.16106023],
        [ 0.95709203]])