In [1]:
from DDPG import DDPG_agent as agt
from canton.misc import get_session
import tensorflow as tf
agent = agt()
agent.alpha

0.9

In [6]:
agent.memory_replay.

1000000

In [3]:
from baselines.ddpg.memoryNIPS import Memory
mem = Memory(1e6,(2,),(2,))

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
agent([1.0])

array([[-0.00179647]], dtype=float32)

In [3]:
sess=get_session()
sess.run(agent.a_infer,feed_dict={agent.observation: [[1.0]]})

array([[-0.00179647]], dtype=float32)

In [4]:
sess=get_session()
sess.run(agent.a2,feed_dict={agent.observation_after: [[1.0]]})

array([[-0.00179647]], dtype=float32)

In [5]:
sess=get_session()
sess.run(agent.target_init_updates)

[None, None]

In [10]:
agent.save_agent()

In [4]:
agent.load_agent()

INFO:tensorflow:Restoring parameters from /tmp/model/model


In [2]:
agent.get_global_variables('actor')

NameError: name 'agent' is not defined

In [5]:
tf.global_variables()

[<tf.Variable 'actor/dense/kernel:0' shape=(1, 64) dtype=float32_ref>,
 <tf.Variable 'actor/dense/bias:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'actor/dense_1/kernel:0' shape=(64, 64) dtype=float32_ref>,
 <tf.Variable 'actor/dense_1/bias:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'actor/dense_2/kernel:0' shape=(64, 1) dtype=float32_ref>,
 <tf.Variable 'actor/dense_2/bias:0' shape=(1,) dtype=float32_ref>]

In [4]:
tf.reset_default_graph()

In [5]:
len(tf.contrib.graph_editor.get_tensors(tf.get_default_graph()))

84

In [6]:
print(tf.contrib.graph_editor.get_tensors(tf.get_default_graph()))

[<tf.Tensor 'observation:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'action:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'observation_after:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'rewards:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'terminals1:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform/shape:0' shape=(2,) dtype=int32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform/min:0' shape=() dtype=float32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform/max:0' shape=() dtype=float32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform/RandomUniform:0' shape=(1, 64) dtype=float32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform/sub:0' shape=() dtype=float32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform/mul:0' shape=(1, 64) dtype=float32>, <tf.Tensor 'actor/dense/kernel/Initializer/random_uniform:0' shape=(1, 64) dtype=float32>, <tf.Tensor 'actor/dense/kernel:0' shape=(1, 64) dtype=float32_ref>, <t

SyntaxError: invalid syntax (<ipython-input-7-7cf15939651b>, line 1)