In [1]:
import numpy as np

In [22]:
a=[1,2,3]
a_array=np.array(a)
print(a_array)

[1 2 3]


In [23]:
print(a_array.T)

[1 2 3]


In [6]:
a_array

array([1, 2, 3])

In [41]:
len(a_array)

3

In [24]:
a_tranpose=np.reshape(a_array,(len(a_array),1))

In [25]:
a_tranpose

array([[1],
       [2],
       [3]])

In [40]:
len(a_tranpose)

3

In [26]:
a_tt=np.reshape(a_tranpose,(1,len(a_tranpose)))

In [27]:
a_tt

array([[1, 2, 3]])

In [38]:
print(a_array)

[1 2 3]


In [39]:
a_array.shape

(3,)

In [37]:
print(a_tranpose)

[[1]
 [2]
 [3]]


In [34]:
a_tranpose.shape

(3, 1)

In [36]:
print(a_tt)

[[1 2 3]]


In [35]:
a_tt.shape

(1, 3)

In [10]:
a_tranpose

array([1, 2, 3])

In [15]:
a_array.shape

(3,)

In [43]:
a=[1,2,3]

In [55]:
b=[-0.03988981353596711,0.0041599475597778835,0.9107809542718925,0.5413419308663239,0.22726946578496612,0.06862863242559152,-0.04658079955331369,0.055459112129451704,0.0278211493268339,-0.034736493283117086]

In [56]:
b

[-0.03988981353596711,
 0.0041599475597778835,
 0.9107809542718925,
 0.5413419308663239,
 0.22726946578496612,
 0.06862863242559152,
 -0.04658079955331369,
 0.055459112129451704,
 0.0278211493268339,
 -0.034736493283117086]

In [18]:
b=a_tranpose.T

In [19]:
b.shape

(3,)

In [44]:
a_array=array_min2d(a)

In [45]:
a_array

array([[1],
       [2],
       [3]])

In [57]:
aa_array=array_min2d(a_array)

In [58]:
aa_array

array([[1],
       [2],
       [3]])

In [59]:
a_array.shape

(3, 1)

In [60]:
b

[-0.03988981353596711,
 0.0041599475597778835,
 0.9107809542718925,
 0.5413419308663239,
 0.22726946578496612,
 0.06862863242559152,
 -0.04658079955331369,
 0.055459112129451704,
 0.0278211493268339,
 -0.034736493283117086]

In [64]:
b_array=array_min2d(b)
b_array
b_dict = {'b_array' : b_array}

In [65]:
b_dict

{'b_array': array([[-0.03988981],
        [ 0.00415995],
        [ 0.91078095],
        [ 0.54134193],
        [ 0.22726947],
        [ 0.06862863],
        [-0.0465808 ],
        [ 0.05545911],
        [ 0.02782115],
        [-0.03473649]])}

In [66]:
[[ 0.77815676  0.87001216  0.97861832  0.79915857  0.46147937  0.7805292
   0.11827443  0.63992101  0.14335328  0.94466889  0.52184832  0.41466194
   0.2645556   0.7742337   0.45615032  0.56843394  0.0187898   0.61763549]]

SyntaxError: invalid syntax (<ipython-input-66-78bcae30c87a>, line 1)

In [42]:
def array_min2d(x):
    x = np.array(x)
    if x.ndim >= 2:
        return x
    return x.reshape(-1, 1)